---

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
    when: ansible_os_family == 'Debian'

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: true
    loop:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: Add gVisor apt key
  shell: >
    curl -fsSL https://gvisor.dev/archive.key | gpg --dearmor -o /usr/share/keyrings/gvisor-archive-keyring.gpg
  args:
    warn: false

- name: Add gVisor repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/gvisor-archive-keyring.gpg] https://storage.googleapis.com/gvisor/releases release main"
    state: present
    filename: gvisor.list
    update_cache: yes
